stages:
  - build
  - test
  - deploy:build
  - deploy
  - notification

cache:
  paths:
    - node_modules/


deploy_release_dev_build:
  image: docker:19.03.12
  stage: build
  only:
    - release/development
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $ACCESS_USER -p $ACCESS_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/$CI_PROJECT_NAME:latest-dev -f Dockerfile.
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$CI_PROJECT_NAME:latest-dev

